"""add article-userfeed association table

Revision ID: 54ed61e0d92e
Revises: 05d93d5bf25a
Create Date: 2024-07-16 20:26:54.896337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ed61e0d92e'
down_revision = '05d93d5bf25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_userfeed',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('userfeed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['userfeed_id'], ['user_feed.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'userfeed_id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=128), nullable=False))

    op.drop_table('article_userfeed')
    # ### end Alembic commands ###
