"""fix article table

Revision ID: d6a777014a1c
Revises: 
Create Date: 2024-06-02 20:13:03.793367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a777014a1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_feed_id', 'feed', ['feed_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('feed_id')

    # ### end Alembic commands ###
